### ISSUE TITLE
Travis SIRF-Superbuild fails

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/github-stats#3]
@casperdcl Travis fails complete at the moment. error is for instance at https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/676099895#L1458

We think the problem is that the branch is called `synerBI` as opposed to `syneRBI`. git branch names are case specific probably?

**Comment by casperdcl** [comment]
closed by aa4369c07d6334fb6b7a7c1dee5bcc093825d37e
